/*

 HINTERGUND2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\User\Desktop\Mein Kram\Gameboy\hintergrund.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BurgWidth 40
#define BurgHeight 18
#define BurgBank 0

extern unsigned char Burg[];

/* End of HINTERGUND2.H */
