/*

 HINTERGRUND1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\User\Desktop\Mein Kram\Gameboy\hintergrund.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define NiceWidth 40
#define NiceHeight 18
#define NiceBank 0

extern unsigned char Nice[];

/* End of HINTERGRUND1.H */
