/*

 SCHWEIN.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0xFF,0x00,0xFF,0x00,0xFF,0x00,0xBD,0x81,
  0xC3,0x00,0xDB,0x24,0xC3,0x00,0xFF,0x00,
  0xFF,0x00,0xFF,0x81,0xFF,0x42,0xBD,0x81,
  0xC3,0x00,0xDB,0x24,0xC3,0x00,0xFF,0x00
};

/* End of SCHWEIN.C */
