/*

 HINTERGRUND1.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\User\Desktop\Mein Kram\Gameboy\hintergrund.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

unsigned char WNice[] =
{
  0x12,0x0B,0x16,0x16,0x19
};

/* End of HINTERGRUND1.C */
